spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techstash_database
    username: root
    password: ganeshwari
    type: org.apache.tomcat.jdbc.pool.DataSource
    maxIdle: 1